version: 2.1
jobs:
  build:
    docker:
      - image:  circleci/node3.0.0
      environment:
        - CHROME_BIN=/usr/bin/google-chrome
    steps:
      - checkout
      - run: npm install
      - run: npm test
